"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {AppShell} from "@/components/AppShell";
import {createClient} from "@/lib/supabase/client";
import {conditions,grades,modes,subjects,type BookCondition,type ListingMode} from "@/lib/books";

export default function SellPage(){
 const router=useRouter();const [userId,setUserId]=useState<string|null>(null);const [files,setFiles]=useState<File[]>([]);const [title,setTitle]=useState("");const [subject,setSubject]=useState<(typeof subjects)[number]>(subjects[0]);const [grade,setGrade]=useState<(typeof grades)[number]>(grades[3]);const [price,setPrice]=useState("");const [condition,setCondition]=useState<BookCondition>("Bom estado");const [city,setCity]=useState("");const [municipality,setMunicipality]=useState("");const [description,setDescription]=useState("");const [mode,setMode]=useState<ListingMode>("Venda");const [loading,setLoading]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{createClient().auth.getUser().then(({data})=>{if(!data.user)router.replace("/auth");else setUserId(data.user.id)})},[router]);
 async function submit(e:React.FormEvent){e.preventDefault();if(!userId)return;setLoading(true);setError("");const supabase=createClient();const {data:book,error:bookError}=await supabase.from("books").insert({seller_id:userId,title,subject,grade,price_kz:Number(price||0),condition,mode,city,municipality,description,is_published:true}).select("id").single();if(bookError||!book){setError(bookError?.message||"Não foi possível publicar.");setLoading(false);return}
  for(let i=0;i<files.slice(0,5).length;i++){const file=files[i];const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]/g,"-");const path=userId+"/"+book.id+"/"+Date.now()+"-"+i+"-"+safe;const upload=await supabase.storage.from("book-images").upload(path,file,{upsert:false,contentType:file.type});if(upload.error){setError("O livro foi criado, mas uma fotografia não pôde ser carregada.");break}await supabase.from("book_images").insert({book_id:book.id,storage_path:path,sort_order:i})}
  setLoading(false);router.push("/books/"+book.id);
 }
 return <AppShell><section className="sell-page container"><span className="eyebrow">PUBLICAR</span><h1>Publique um livro.</h1><p className="lead">Ajude outro estudante a encontrar o livro de que precisa.</p><form className="sell-form" onSubmit={submit}><label className="upload-zone"><input type="file" accept="image/*" multiple hidden onChange={e=>setFiles(Array.from(e.target.files||[]).slice(0,5))}/><span>＋</span><strong>{files.length?files.length+" fotografia(s) seleccionada(s)":"Adicionar fotografias"}</strong><small>Até 5 fotografias · JPG, PNG ou WebP</small></label><label>Título do livro<input value={title} onChange={e=>setTitle(e.target.value)} required placeholder="Ex.: Matemática 10ª Classe"/></label><div className="form-two"><label>Disciplina<select value={subject} onChange={e=>setSubject(e.target.value as typeof subject)}>{subjects.map(x=><option key={x}>{x}</option>)}</select></label><label>Classe<select value={grade} onChange={e=>setGrade(e.target.value as typeof grade)}>{grades.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="form-two"><label>Preço (Kz)<input type="number" min="0" value={price} onChange={e=>setPrice(e.target.value)} placeholder="8000"/></label><label>Estado<select value={condition} onChange={e=>setCondition(e.target.value as BookCondition)}>{conditions.map(x=><option key={x}>{x}</option>)}</select></label></div><div className="form-two"><label>Cidade<input value={city} onChange={e=>setCity(e.target.value)} placeholder="Lobito"/></label><label>Município<input value={municipality} onChange={e=>setMunicipality(e.target.value)} placeholder="Lobito"/></label></div><label>Descrição<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4} placeholder="Estado, edição, observações..."/></label><div className="listing-type"><strong>Como pretende disponibilizar?</strong><div>{modes.map(x=><button type="button" className={mode===x?"selected":""} key={x} onClick={()=>setMode(x)}>{x}</button>)}</div></div>{error&&<div className="form-error">{error}</div>}<button className="button submit-listing" disabled={loading}>{loading?"A publicar...":"Publicar livro →"}</button></form></section></AppShell>;
}
